services:
  acarsdec2:
    image: ${ACARSDEC_CONTAINER}
    container_name: acarsdec2
    hostname: acarsdec2
    restart: unless-stopped
    healthcheck:
      disable: true
    environment:
      # - QUIET_LOGS=true
      - TZ=${FEEDER_TZ}
      - SOAPYSDR=${ACARS2_SDR_STRING}
      - GAIN=${ACARS2_GAIN}
      # the default frequencies are 'acarsdec has the the more common frequencies above 130MHz, acarsdec2 has the less common frequencies starting at 128.975MHz
      - FREQUENCIES=${ACARS2_FREQUENCIES:-128.975 129.000 129.125 129.350 129.525}
      - FEED_ID=${ACARS2_FEED_ID}
      - OUTPUT_SERVER=acars_router
      - OUTPUT_SERVER_MODE=tcp
      # USER_PROVIDED_ENV_START
      # USER_PROVIDED_ENV_END
    tmpfs:
      - /run:exec,size=64M
      - /var/log:size=64M
    device_cgroup_rules:
      - "c 189:* rwm"
    volumes:
      - /dev/bus/usb:/dev/bus/usb:ro
