services:
  dumphfdl:
    image: ${DUMPHFDL_CONTAINER}
    container_name: dumphfdl
    healthcheck:
      disable: true
    restart: unless-stopped
    device_cgroup_rules:
      - "c 189:* rwm"
    environment:
      - TZ=${FEEDER_TZ}
      - SOAPYSDRDRIVER=${HFDL_SDR_STRING}
      - GAIN_TYPE=${HFDL_GAIN_TYPE}
      - GAIN=${HFDL_GAIN}
      - SOAPYSAMPLERATE=${HFDL_SAMPLERATE:-768000}
      - FEED_ID=${HFDL_FEED_ID}
      - FREQUENCIES=${HFDL_FREQUENCIES}
      - ZMQ_MODE=server
      - ZMQ_ENDPOINT=tcp://0.0.0.0:45555
      - SERVER=acars_router
      - SERVER_PORT=5556
    tmpfs:
      - /run:exec,size=64M
      - /var/log
      - /tmp
    volumes:
      - /dev:/dev:ro
      - /opt/adsb/data/dumphfdl-data:/opt/dumphfdl
      - /opt/adsb/data/dumphfdl-scanner:/opt/scanner
